// Products Action Types
export const PRODUCTS_SET_LOADING = 'PRODUCTS_SET_LOADING';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_SET_CATEGORIES = 'PRODUCTS_SET_CATEGORIES';
export const PRODUCTS_SET_CURRENT = 'PRODUCTS_SET_CURRENT';
export const PRODUCTS_CLEAR = 'PRODUCTS_CLEAR';
export const PRODUCTS_SET_PAGINATION = 'PRODUCTS_SET_PAGINATION';

